name: Run version script on release

on:
  push:
    tags:
      - 'v*'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run version script
        env:
          OUTLINE_TOKEN: ${{ secrets.OUTLINE_TOKEN }}
          SEAFILE_USERNAME: ${{ secrets.SEAFILE_USERNAME }}
          SEAFILE_PASSWORD: ${{ secrets.SEAFILE_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python VersionsUpdateForOutline.py